# Generated by Django 5.2.3 on 2025-06-27 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Discount cannot be negative.'), django.core.validators.MaxValueValidator(100, message='Discount cannot exceed 100.')]),
        ),
    ]
