# Generated by Django 5.2.3 on 2025-06-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
