# Generated by Django 5.2.3 on 2025-06-27 07:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_product_actual_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Discount cannot be negative.'), django.core.validators.MaxValueValidator(100, message='Discount cannot exceed 100.')])),
                ('provider', models.CharField(default='', max_length=100)),
                ('coupon_code', models.CharField(default='', max_length=50, unique=True)),
                ('allowed_users', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Users cannot be negative.')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product')),
            ],
        ),
    ]
