# Generated by Django 5.2.3 on 2025-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_product_discount_discounts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='coupon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
