# Generated by Django 5.2.3 on 2025-06-27 10:28

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_cartitem_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='discounts',
            name='current_users',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Users cannot be negative.')]),
        ),
        migrations.AddField(
            model_name='discounts',
            name='expiry',
            field=models.DurationField(default=datetime.timedelta(days=10, seconds=68400)),
        ),
    ]
