# Generated by Django 5.2.3 on 2025-06-27 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_discounts_created_at_discounts_current_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 16, 3, 14, 205403)),
        ),
    ]
