# Generated by Django 5.2.3 on 2025-06-27 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_discounts_updated_at_alter_discounts_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discounts',
            old_name='current_users',
            new_name='used',
        ),
        migrations.AlterField(
            model_name='discounts',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 16, 12, 45, 670638)),
        ),
    ]
