# Generated by Django 5.2.3 on 2025-06-27 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_rename_current_users_discounts_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 17, 0, 30, 69190)),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
